#! /usr/bin/env bash

IFS=$'\n' read -d '' -r -a animals < animals

IFS=$'\n' read -d '' -r -a adjectives < adjectives

nbAnimals=${#animals[@]}
nbAdjectives=${#adjectives[@]}
selectedAnimal=${animals[$(($RANDOM % nbAnimals))]}
selectedAdjective=${adjectives[$(($RANDOM % nbAdjectives))]}
echo "${selectedAdjective}_${selectedAnimal}"
